### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by anirudha**
updated readme with naming changes and links to documentation for Amazon Elasticsearch service and Open Distro

### CODE REVIEW

**Comment by anirudha** [comment]
@robdiciuccio  @syamat @mistercrunch @dioptre @srinify 
please help here on this PR

 let us know if you need us to help in any way on this feature support. My team maintains and own the opendistro SQL plugin

**Comment by dpgaspar** [comment]
@anirudha,

Feel free to reach out, would really love to fully support opendistro but the results from the SQL endpoint are totally different from the Elasticsearch endpoint (unless this has changed recently). It's more complex to transform pure ES results to a row structure, and that's whats missing

**Comment by dioptre** [comment]
@dpgaspar would it be best to fork the project? I haven't been able to use dbapi successfully at all so far. 

Would be nice to understand from your perspective what's needed.

**Comment by dpgaspar** [comment]
@dioptre do you have any open issue?

**Comment by dioptre** [comment]
Here's my issue that's been open for 5 months.

https://github.com/preset-io/elasticsearch-dbapi/issues/31

Thanks @dpgaspar

**Comment by syamat** [comment]
I would also like to contribute to have opendistro support enabled. I have filed the below issue.

#5

**Pull request merged**
