### PR TITLE
Make `fetch_size` configurable and set default to 10000

### PR DESCRIPTION
**Pull request by Alexander-N**
Explicitly give `fetch_size` as parameter for the Elasticsearch request
since otherwise it's impossible to fetch more than 1000 rows, which is
the default value if the parameter is not given. [1]

Set the default to 10000 since that's also the default for
`max_result_window`. [2]

[1] https://www.elastic.co/guide/en/elasticsearch/reference/7.x/sql-rest-fields.html#sql-rest-fields
[2] https://www.elastic.co/guide/en/elasticsearch/reference/7.x/index-modules.html#dynamic-index-settings

### CODE REVIEW

**Comment by willbarrett** [comment]
Seems reasonable to me, but it would be good to get @dpgaspar 's take on it as well.

**Comment by Alexander-N** [comment]
Is there any chance to move on without @dpgaspar review?

**Review by dpgaspar — COMMENTED** [review]
LGTM, small detail, can you drop a comment on README about `fetch_size` and how to override the default?

**Review by dpgaspar — APPROVED** [review]

**Comment by dpgaspar** [comment]
@Alexander-N Thank you!

**Pull request merged**
